#name = input("Enter your full name: ")
#num = input("Enter your phone number: ")
#z = len(name)
#z = name.find("m")
#z = name.rfind("m")
#z = name.capitalize()
#z = name.upper()
#z = name.lower()
#z = name.isdigit()
#z = name.isalpha()
#z = name.isalpha()

#z = num.count("-")
#z = num.replace("-","+")
print(help(str))
#print(z)